### ISSUE TITLE
Publisher page not found

### ISSUE THREAD

**Issue by jafluri** [tensorflow/tfhub.dev#105]
Hello,

I just noticed that when I go to the publisher pages: https://tfhub.dev/s?subtype=publisher
the link to the publisher page of the cosmo-group-ethz: https://tfhub.dev/cosmo-group-ethz
throws a 404. Is there something wrong with the `cosmo-group-ethz.md` that we submitted recently or is this related to something else?

**Comment by maringeo** [comment]
Hi @jafluri, the problem is that https://github.com/tensorflow/tfhub.dev/pull/99/files#diff-50a2b866c16da0898e05f82948c92bef8c36dc4c684c3ffc62d74c2f7d86603d is missing the publisher display name. The publisher display name is added on a line immediately after the first line, however for cosmo-group-ethz the content is:
```
# Publisher cosmo-group-ethz

[![Icon URL]]...
```
You can fix this by changing the md file to:

```
# Publisher cosmo-group-ethz
placeholder text: insert some display name for cosmo-group-ethz publisher

[![Icon URL]]...
```

As an example, here is the md file for another publisher: https://raw.githubusercontent.com/tensorflow/tfhub.dev/master/assets/docs/captain-pool/captain-pool.md

Alternatively, feel free to just tell me what the desired display name for the cosmo-group-ethz publisher is and I can submit the change.

**Comment by jafluri** [comment]
Thanks a lot for looking into this, I didn't notice the display name!

It would be great if you could add the display name: Cosmology Research Group (ETH Zurich)

**Comment by maringeo** [comment]
Thank you @jafluri. Done in https://github.com/tensorflow/tfhub.dev/commit/ee43536536ad1090ee2e296d58eacc6e3eaa0926.
